import type { KnowledgeSeed } from './types';

/** 周易、京房、六爻核心典籍 */
export const CLASSICS_BAGUA: KnowledgeSeed[] = [
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 屯卦',
    content: '元亨利贞。勿用有攸往，利建侯。屯者难也，物始生而未通。君子以经纶，处险而不失其正。',
    metadata: { source: '易经', hexagram: '屯', seed_key: 'bagua:屯' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 蒙卦',
    content: '匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。君子以果行育德。',
    metadata: { source: '易经', hexagram: '蒙', seed_key: 'bagua:蒙' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 需卦',
    content: '有孚，光亨，贞吉。利涉大川。云上于天，需；君子以饮食宴乐。待时而动，不可躁进。',
    metadata: { source: '易经', hexagram: '需', seed_key: 'bagua:需' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 讼卦',
    content: '有孚窒惕，中吉，终凶。利见大人，不利涉大川。君子以作事谋始。争讼之道，宜止不宜长。',
    metadata: { source: '易经', hexagram: '讼', seed_key: 'bagua:讼' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 谦卦',
    content: '亨，君子有终。天道下济而光明，地道卑而上行。君子以裒多益寡，称物平施。',
    metadata: { source: '易经', hexagram: '谦', seed_key: 'bagua:谦' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 豫卦',
    content: '利建侯行师。雷出地奋，豫；先王以作乐崇德，殷荐之上帝，以配祖考。豫者顺也，顺以动。',
    metadata: { source: '易经', hexagram: '豫', seed_key: 'bagua:豫' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 随卦',
    content: '元亨利贞，无咎。泽雷随；君子以向晦入宴息。随时之义大矣哉！知进退存亡而不失其正者，其惟圣人乎。',
    metadata: { source: '易经', hexagram: '随', seed_key: 'bagua:随' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 蛊卦',
    content: '元亨，利涉大川。先甲三日，后甲三日。山下有风，蛊；君子以振民育德。拯弊治乱，在革故鼎新。',
    metadata: { source: '易经', hexagram: '蛊', seed_key: 'bagua:蛊' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 临卦',
    content: '元亨利贞。至于八月有凶。泽上有地，临；君子以教思无穷，容保民无疆。临事而惧，好谋而成。',
    metadata: { source: '易经', hexagram: '临', seed_key: 'bagua:临' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 观卦',
    content: '盥而不荐，有孚颙若。风行地上，观；先王以省方观民设教。观其所生，察其所由。',
    metadata: { source: '易经', hexagram: '观', seed_key: 'bagua:观' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 泰卦',
    content: '小往大来，吉亨。天地交，泰；后以财成天地之道，辅相天地之宜，以左右民。通泰之时，宜广施德泽。',
    metadata: { source: '易经', hexagram: '泰', wuxing: '土', seed_key: 'bagua:泰' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 否卦',
    content: '否之匪人，不利君子贞，大往小来。天地不交，否；君子以俭德辟难，不可荣以禄。闭塞之时，宜守正待变。',
    metadata: { source: '易经', hexagram: '否', seed_key: 'bagua:否' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 同人卦',
    content: '同人于野，亨。利涉大川，利君子贞。天与火，同人；君子以类族辨物。和同之道，在公不在私。',
    metadata: { source: '易经', hexagram: '同人', seed_key: 'bagua:同人' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 大有卦',
    content: '元亨。火在天上，大有；君子以遏恶扬善，顺天休命。大有之时，宜藏器于身，待时而动。',
    metadata: { source: '易经', hexagram: '大有', wuxing: '火', seed_key: 'bagua:大有' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 震卦',
    content: '亨。震来虩虩，笑言哑哑。震惊百里，不丧匕鬯。洊雷，震；君子以恐惧修省。动而有常，惧而后安。',
    metadata: { source: '易经', hexagram: '震', wuxing: '木', seed_key: 'bagua:震' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 艮卦',
    content: '艮其背，不获其身，行其庭，不见其人，无咎。兼山，艮；君子以思不出其位。知止而后有定。',
    metadata: { source: '易经', hexagram: '艮', wuxing: '土', seed_key: 'bagua:艮' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 巽卦',
    content: '小亨，利有攸往，利见大人。随风，巽；君子以申命行事。巽者入也，柔顺而不失正，方能深入。',
    metadata: { source: '易经', hexagram: '巽', wuxing: '木', seed_key: 'bagua:巽' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 兑卦',
    content: '亨，利贞。丽泽，兑；君子以朋友讲习。说而后民劝，和悦以行义，非佞媚之谓。',
    metadata: { source: '易经', hexagram: '兑', wuxing: '金', seed_key: 'bagua:兑' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 系辞下传',
    content: '吉凶者，失得之象也；悔吝者，忧虞之象也；变化者，进退之象也。是故君子安而不忘危，存而不忘亡，治而不忘乱。',
    metadata: { source: '易经', section: '系辞下', seed_key: 'bagua:系辞下' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 说卦传',
    content: '昔者圣人之作易也，将以顺性命之理。是以立天之道曰阴与阳，立地之道曰柔与刚，立人之道曰仁与义。',
    metadata: { source: '易经', section: '说卦', seed_key: 'bagua:说卦' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '京房易传 · 纳甲法要',
    content: '八宫卦气，世应定主客。乾宫属金，坎宫属水，艮宫属土，震宫属木，巽宫属木，离宫属火，坤宫属土，兑宫属金。纳甲以干支配爻，定五行生克。',
    metadata: { source: '京房易传', topic: '纳甲', seed_key: 'bagua:京房纳甲' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '增删卜易 · 旺衰论',
    content: '月建为提纲，日辰为主宰。旺相则力盛，休囚则力衰。动爻化进神则势增，化退神则势减。断事必先看旺衰，再看生克。',
    metadata: { source: '增删卜易', topic: '六爻', seed_key: 'bagua:旺衰' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '增删卜易 · 用神取法',
    content: '问财以财爻为用，问官以官爻为用，问婚以世应为用。用神旺相有气则吉，休囚无气则滞。用神受克则事阻，得生则事顺。',
    metadata: { source: '增删卜易', topic: '六爻', seed_key: 'bagua:用神' },
  },
];
