import type { KnowledgeSeed } from './types';

/** 道家、内丹、养生典籍 */
export const CLASSICS_DAO: KnowledgeSeed[] = [
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 道法自然',
    content: '人法地，地法天，天法道，道法自然。自然者，非造作之谓，乃本然之序。知自然则不强求，不强求则与天理相契。',
    metadata: { source: '道德经', chapter: 25, seed_key: 'dao:25' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 反者道之动',
    content: '反者道之动，弱者道之用。天下万物生于有，有生于无。知盛极而衰、否极泰来，方能在变局中守中。',
    metadata: { source: '道德经', chapter: 40, seed_key: 'dao:40' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 知足不辱',
    content: '祸莫大于不知足，咎莫大于欲得。故知足之足，常足矣。命数推演之旨，在知止知足，非纵欲逆天。',
    metadata: { source: '道德经', chapter: 46, seed_key: 'dao:46' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 大成若缺',
    content: '大成若缺，其用不弊。大盈若冲，其用不穷。大直若屈，大巧若拙，大辩若讷。真机往往在似缺似拙处。',
    metadata: { source: '道德经', chapter: 45, seed_key: 'dao:45' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 持而盈之',
    content: '持而盈之，不如其已。揣而锐之，不可长保。金玉满堂，莫之能守。富贵而骄，自遗其咎。功成身退，天之道。',
    metadata: { source: '道德经', chapter: 9, seed_key: 'dao:9' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '庄子 · 大宗师',
    content: '夫大块载我以形，劳我以生，佚我以老，息我以死。故善吾生者，乃所以善吾死也。知生死为一贯，则命数可观而不可惧。',
    metadata: { source: '庄子', chapter: '大宗师', seed_key: 'dao:大宗师' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '庄子 · 人间世',
    content: '知其不可奈何而安之若命，德之至也。命有定分而有活路，安命非躺平，乃在界限内尽其性。',
    metadata: { source: '庄子', chapter: '人间世', seed_key: 'dao:人间世' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '庄子 · 德充符',
    content: '知其不可奈何而安之若命，唯有德者能之。德充乎形，不矜于外。命格或囿于五行，德性可破形骸之限。',
    metadata: { source: '庄子', chapter: '德充符', seed_key: 'dao:德充符' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '列子 · 天瑞',
    content: '有生不生，有化不化。不生者能生生，不化者能化化。命数如化化之机，观变而不失其宗。',
    metadata: { source: '列子', chapter: '天瑞', seed_key: 'dao:天瑞' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '黄庭经 · 内观',
    content: '闭目内视，五气自朝。心闭三关，三气自朝。回光返照，神归于根。修身与推命相表里，气定则神清，神清则判断不妄。',
    metadata: { source: '黄庭经', seed_key: 'dao:内观' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '悟真篇 · 性命双修',
    content: '命者性之根，性者命之苗。先修命则性可养，先修性则命可固。推命知格局，修行改气质，二者合参乃正道。',
    metadata: { source: '悟真篇', seed_key: 'dao:性命' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '抱朴子 · 内篇',
    content: '善摄生者，先除六害，后行十二少。六害者，名利、声色、滋味、货财、强梁、诡诈。去害则命基自固。',
    metadata: { source: '抱朴子', seed_key: 'dao:抱朴子' },
  },
  {
    type: 'classic',
    tradition: 'neijing',
    title: '黄帝内经 · 四气调神',
    content: '春三月，此谓发陈。天地俱生，万物以荣，夜卧早起，广步于庭。逆之则伤肝。顺四时而养，与推命之四季纲要相合。',
    metadata: { source: '黄帝内经', chapter: '四气调神大论', wuxing: '木', seed_key: 'neijing:四气' },
  },
  {
    type: 'classic',
    tradition: 'neijing',
    title: '黄帝内经 · 上古天真',
    content: '上古之人，其知道者，法于阴阳，和于术数，食饮有节，起居有常，不妄作劳，故能形与神俱，而尽终其天年。',
    metadata: { source: '黄帝内经', chapter: '上古天真论', seed_key: 'neijing:天真' },
  },
  {
    type: 'classic',
    tradition: 'neijing',
    title: '黄帝内经 · 阴阳应象',
    content: '阴阳者，天地之道也，万物之纲纪，变化之父母，生杀之本始，神明之府也。推命之本，在辨阴阳消长。',
    metadata: { source: '黄帝内经', chapter: '阴阳应象大论', seed_key: 'neijing:阴阳' },
  },
  {
    type: 'classic',
    tradition: 'neijing',
    title: '难经 · 一难',
    content: '十二经皆有动脉，独取寸口以决五脏六腑死生吉凶之法，何谓也？然寸口者，脉之大会，手太阴之脉动也。',
    metadata: { source: '难经', seed_key: 'neijing:难经' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '太上感应篇',
    content: '祸福无门，惟人自召；善恶之报，如影随形。命数非铁板，德行可转气机。推命当知因果，劝人迁善。',
    metadata: { source: '太上感应篇', seed_key: 'dao:感应' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '阴符经 · 观天之道',
    content: '观天之道，执天之行，尽矣。天发杀机，移星易宿；地发杀机，龙蛇起陆；人发杀机，天地反覆。天人合发，万变定基。',
    metadata: { source: '阴符经', seed_key: 'dao:阴符' },
  },
];
