import type { KnowledgeSeed } from './types';

/** 子平、三命、穷通等命理典籍 */
export const CLASSICS_BAZI: KnowledgeSeed[] = [
  {
    type: 'classic',
    tradition: 'bazi',
    title: '子平真诠 · 论格局',
    content: '八字用神，专求月令。月令司权，当权者旺。以日干配月令，察其生克得失，定格局高低。格局清则贵，浊则贱。',
    metadata: { source: '子平真诠', topic: '格局', seed_key: 'bazi:格局' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '子平真诠 · 论用神',
    content: '用神者，日主之所喜也。扶抑、调候、通关、从格，各因其局而定。用神有力则吉，用神受伤则凶，非一成不变。',
    metadata: { source: '子平真诠', topic: '用神', seed_key: 'bazi:用神' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '渊海子平 · 论天干',
    content: '天干动而不居，主外象。甲乙东方木，丙丁南方火，戊己中央土，庚辛西方金，壬癸北方水。天干合化，须得月令之气。',
    metadata: { source: '渊海子平', wuxing: '木', seed_key: 'bazi:天干' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '渊海子平 · 论地支',
    content: '地支静而主内。子水、丑土、寅木、卯木、辰土、巳火、午火、未土、申金、酉金、戌土、亥水。地支三合、三会、六合、六冲，定人事离合。',
    metadata: { source: '渊海子平', seed_key: 'bazi:地支' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '三命通会 · 论纳音',
    content: '纳音者，六十甲子配五行之声。如甲子乙丑海中金，丙寅丁卯炉中火。纳音可参格局气势，不可独断吉凶。',
    metadata: { source: '三命通会', seed_key: 'bazi:纳音' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '三命通会 · 论大运',
    content: '大运如行路，十年一换。阳男阴女顺排，阴男阳女逆排。大运与命局、流年合参，方见十年吉凶之机。',
    metadata: { source: '三命通会', seed_key: 'bazi:大运' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '穷通宝鉴 · 论木',
    content: '甲木参天，脱胎要火。春不容金，秋不容土。火炽乘龙，水宕骑虎。地润天和，植立千古。木命春生宜火，秋生宜金。',
    metadata: { source: '穷通宝鉴', wuxing: '木', element: '木', seed_key: 'bazi:木' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '穷通宝鉴 · 论火',
    content: '丙火猛烈，欺霜侮雪。能煅庚金，逢辛反怯。土众成慈，水猖显节。虎马犬乡，甲来成灭。火命夏旺，冬生宜木。',
    metadata: { source: '穷通宝鉴', wuxing: '火', element: '火', seed_key: 'bazi:火' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '穷通宝鉴 · 论土',
    content: '戊土固重，既中且正。静翕动辟，万物司命。水润物生，火燥物病。若在艮坤，怕冲宜静。土命四季旺，宜水润木疏。',
    metadata: { source: '穷通宝鉴', wuxing: '土', element: '土', seed_key: 'bazi:土' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '穷通宝鉴 · 论金',
    content: '庚金带煞，刚健为最。得水而清，得火而锐。土润则生，土干则脆。能赢甲兄，输于乙妹。金命秋旺，春生宜火炼。',
    metadata: { source: '穷通宝鉴', wuxing: '金', element: '金', seed_key: 'bazi:金' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '穷通宝鉴 · 论水',
    content: '壬水通河，能泄金气。刚中之德，周流不滞。通根透癸，冲天奔地。化则有情，从则相济。水命冬旺，夏生宜金源。',
    metadata: { source: '穷通宝鉴', wuxing: '水', element: '水', seed_key: 'bazi:水' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '滴天髓 · 论格局清浊',
    content: '清者，用神纯粹不杂；浊者，混杂无救。清则贵，浊则贱。然清浊亦随大运流年而变，不可执一。',
    metadata: { source: '滴天髓', seed_key: 'bazi:清浊' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '滴天髓 · 论从与化',
    content: '从则从化神为用，化则合而成功。从格宜顺，逆则凶。化格须真，假化不如不化。从化之格，十不出一。',
    metadata: { source: '滴天髓', seed_key: 'bazi:从化' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '神峰通考 · 病药说',
    content: '命局有病方为贵，有药方为吉。病者，过旺过弱、冲克刑害；药者，用神、喜神、制化之神。先看病，后取药。',
    metadata: { source: '神峰通考', seed_key: 'bazi:病药' },
  },
  {
    type: 'classic',
    tradition: 'bazi',
    title: '星平会海 · 论神煞',
    content: '神煞者，干支特殊组合之符号。桃花、驿马、华盖、贵人等，可作辅助参考，不可喧宾夺主，盖煞乃用神之枝叶。',
    metadata: { source: '星平会海', seed_key: 'bazi:神煞' },
  },
  {
    type: 'classic',
    tradition: 'wuxing',
    title: '五行大义 · 生克',
    content: '木生火，火生土，土生金，金生水，水生木。木克土，土克水，水克火，火克金，金克木。生克循环，造化无穷，推命之本。',
    metadata: { source: '五行大义', seed_key: 'wuxing:生克' },
  },
  {
    type: 'classic',
    tradition: 'calendar',
    title: '协纪辨方书 · 择日纲要',
    content: '用事必择吉日良辰。以建除、黄道黑道、神煞、干支冲合参之。推命与择日同源，皆本于干支历法与天地气机。',
    metadata: { source: '协纪辨方书', seed_key: 'calendar:择日' },
  },
  {
    type: 'classic',
    tradition: 'fengshui',
    title: '葬书 · 气感说',
    content: '气乘风则散，界水则止。古人聚之使不散，行之使有止，故谓之风水。推命知人事之机，风水知环境之势，二者可互证。',
    metadata: { source: '葬书', seed_key: 'fengshui:葬书' },
  },
];
