import type { KnowledgeSeed } from './types';

/** 命理术数核心术语 */
export const GLOSSARY_CORE: KnowledgeSeed[] = [
  { type: 'glossary', tradition: 'bazi', title: '天干', content: '甲乙丙丁戊己庚辛壬癸十天干，主外在气机与表象，配合地支成六十甲子。', metadata: { term: '天干', seed_key: 'gloss:天干' } },
  { type: 'glossary', tradition: 'bazi', title: '地支', content: '子丑寅卯辰巳午未申酉戌亥十二地支，主内在根基与藏干，司时令方位。', metadata: { term: '地支', seed_key: 'gloss:地支' } },
  { type: 'glossary', tradition: 'bazi', title: '藏干', content: '地支中所藏天干，如子藏癸、丑藏己癸辛。藏干透干则力显，不透则力隐。', metadata: { term: '藏干', seed_key: 'gloss:藏干' } },
  { type: 'glossary', tradition: 'bazi', title: '月令', content: '出生月支，为命局提纲。月令司权，定五行旺衰，格局高低首看月令。', metadata: { term: '月令', seed_key: 'gloss:月令' } },
  { type: 'glossary', tradition: 'bazi', title: '日主', content: '日干代表命主自身，一切十神、用神皆相对于日主而论。', metadata: { term: '日主', seed_key: 'gloss:日主' } },
  { type: 'glossary', tradition: 'bazi', title: '身旺身弱', content: '日主在月令及全局中的强弱。身旺宜克泄耗，身弱宜印比生扶；从格另论。', metadata: { term: '身旺身弱', seed_key: 'gloss:身旺' } },
  { type: 'glossary', tradition: 'bazi', title: '喜用神', content: '对命局最有益的五行或十神。扶抑、调候、通关、从格各有不同取法。', metadata: { term: '喜用神', seed_key: 'gloss:喜用神' } },
  { type: 'glossary', tradition: 'bazi', title: '忌神', content: '损害用神或助旺忌神之五行。忌神当令则凶机显，受制则祸患轻。', metadata: { term: '忌神', seed_key: 'gloss:忌神' } },
  { type: 'glossary', tradition: 'bazi', title: '三合局', content: '申子辰合水、亥卯未合木、寅午戌合火、巳酉丑合金。合则力量汇聚，可成化局。', metadata: { term: '三合', seed_key: 'gloss:三合' } },
  { type: 'glossary', tradition: 'bazi', title: '三会局', content: '寅卯辰会东方木、巳午未会南方火、申酉戌会西方金、亥子丑会北方水。', metadata: { term: '三会', seed_key: 'gloss:三会' } },
  { type: 'glossary', tradition: 'bazi', title: '六冲', content: '子午冲、丑未冲、寅申冲、卯酉冲、辰戌冲、巳亥冲。冲则动、变、散，吉凶因局而异。', metadata: { term: '六冲', seed_key: 'gloss:六冲' } },
  { type: 'glossary', tradition: 'bazi', title: '六合', content: '子丑合、寅亥合、卯戌合、辰酉合、巳申合、午未合。合则亲、绊、化，视化神而定。', metadata: { term: '六合', seed_key: 'gloss:六合' } },
  { type: 'glossary', tradition: 'bazi', title: '三刑', content: '寅巳申三刑、丑戌未三刑、子卯刑、辰午酉亥自刑。刑主伤、讼、阻，亦主变革。', metadata: { term: '三刑', seed_key: 'gloss:三刑' } },
  { type: 'glossary', tradition: 'bazi', title: '六害', content: '子未害、丑午害、寅巳害、卯辰害、申亥害、酉戌害。害则暗伤、猜忌、暗中阻滞。', metadata: { term: '六害', seed_key: 'gloss:六害' } },
  { type: 'glossary', tradition: 'bazi', title: '空亡', content: '旬空之支，力量虚空或事多虚浮。逢填实、冲空则力复。', metadata: { term: '空亡', seed_key: 'gloss:空亡' } },
  { type: 'glossary', tradition: 'bazi', title: '桃花', content: '子午卯酉为四桃花。主异性缘、人缘、艺术气质；过旺则情欲纷扰。', metadata: { term: '桃花', seed_key: 'gloss:桃花' } },
  { type: 'glossary', tradition: 'bazi', title: '驿马', content: '申子辰马在寅，寅午戌马在申，巳酉丑马在亥，亥卯未马在巳。主变动、出行、迁移。', metadata: { term: '驿马', seed_key: 'gloss:驿马' } },
  { type: 'glossary', tradition: 'bazi', title: '华盖', content: '寅午戌见戌，申子辰见辰，巳酉丑见丑，亥卯未见未。主孤高、艺术、宗教缘。', metadata: { term: '华盖', seed_key: 'gloss:华盖' } },
  { type: 'glossary', tradition: 'bazi', title: '天乙贵人', content: '甲戊庚牛羊，乙己鼠猴乡，丙丁猪鸡位，壬癸兔蛇藏，六辛逢马虎。贵人主逢凶化吉、得人相助。', metadata: { term: '天乙贵人', seed_key: 'gloss:贵人' } },
  { type: 'glossary', tradition: 'bazi', title: '羊刃', content: '甲刃在卯，丙戊刃在午，庚刃在酉，壬刃在子。刃主刚烈、竞争、伤灾，宜制化。', metadata: { term: '羊刃', seed_key: 'gloss:羊刃' } },
  { type: 'glossary', tradition: 'bazi', title: '禄神', content: '甲禄寅、乙禄卯、丙戊禄巳、丁己禄午、庚禄申、辛禄酉、壬禄亥、癸禄子。禄为俸禄、根基、福分。', metadata: { term: '禄神', seed_key: 'gloss:禄神' } },
  { type: 'glossary', tradition: 'bazi', title: '纳音五行', content: '六十甲子各配一纳音五行，如海中金、炉中火。参格局气势，辅助论命。', metadata: { term: '纳音', seed_key: 'gloss:纳音' } },
  { type: 'glossary', tradition: 'bazi', title: '真太阳时', content: '按出生地经度校正北京时间，得真实太阳位置。时辰不准则四柱偏差，推命首重真太阳时。', metadata: { term: '真太阳时', seed_key: 'gloss:真太阳时' } },
  { type: 'glossary', tradition: 'bazi', title: '节气', content: '二十四节气划分月令，立春为年界。月支以节气为界，非农历初一。', metadata: { term: '节气', seed_key: 'gloss:节气' } },
  { type: 'glossary', tradition: 'bazi', title: '长生十二宫', content: '长生、沐浴、冠带、临官、帝旺、衰、病、死、墓、绝、胎、养。描述五行在地支的状态循环。', metadata: { term: '长生', seed_key: 'gloss:长生' } },
  { type: 'glossary', tradition: 'bagua', title: '动爻', content: '六爻卦中变化之爻，为事机发动之处。动则变，变则生吉凶之机。', metadata: { term: '动爻', seed_key: 'gloss:动爻' } },
  { type: 'glossary', tradition: 'bagua', title: '用神（六爻）', content: '所问之事在卦中的代表爻。问财看财爻，问官看官爻，用神旺相有气则事成。', metadata: { term: '用神六爻', seed_key: 'gloss:用神爻' } },
  { type: 'glossary', tradition: 'bagua', title: '月建', content: '六爻以月支为月建，定爻之旺衰。月建生扶则旺，月建冲克则衰。', metadata: { term: '月建', seed_key: 'gloss:月建' } },
  { type: 'glossary', tradition: 'tianli', title: '太岁', content: '流年干支，为当年天地气机之主。太岁与命局、大运冲合，定全年主题。', metadata: { term: '太岁', seed_key: 'gloss:太岁' } },
  { type: 'glossary', tradition: 'tianli', title: '天人感应', content: '天地之气与人事相应。出生时刻天地之气入命，运行之时与流年大运交感而生吉凶。', metadata: { term: '天人感应', seed_key: 'gloss:天人' } },
];
