import type { KnowledgeSeed } from './types';

/** 天理推演原则 — 系统释象与推命之根本法则 */
export const PRINCIPLES_TIANLI: KnowledgeSeed[] = [
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 一阴一阳之谓道',
    content: '《系辞》云：一阴一阳之谓道。推命不可执一端，旺中有衰，吉中有慎。观对立统一，方合天理。',
    metadata: { principle: '阴阳', seed_key: 'tianli:阴阳' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 穷理尽性以至于命',
    content: '《中庸》：天命之谓性，率性之谓道，修道之谓教。穷理尽性以至于命——先明理、尽本性，方能知命而不惑。',
    metadata: { principle: '知命', seed_key: 'tianli:穷理' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 吉凶悔吝生乎动',
    content: '《系辞》：吉凶者，失得之象也；悔吝者，忧虞之象也。动则变，变则有机遇有风险。推命旨在知动之时机，非禁动也。',
    metadata: { principle: '动静', seed_key: 'tianli:吉凶' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 变易不易简易',
    content: '易有简易、变易、不易三义。现象万变（变易），规律恒在（不易），大道至简（简易）。推命观变而求其不易。',
    metadata: { principle: '三易', seed_key: 'tianli:三易' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 天人相应',
    content: '董仲舒：天人相感相应。人命与天地气机同频，出生之时为根，运行之时为应。流年流月，皆天人交感之迹。',
    metadata: { principle: '天人', seed_key: 'tianli:天人' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 道法自然',
    content: '老子：人法地，地法天，天法道，道法自然。推命之终，在教人顺性而为、不逆天理之序，非宿命论。',
    metadata: { principle: '自然', seed_key: 'tianli:自然' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 盛极而衰',
    content: '物极必反，亢龙有悔。五行过旺则宜泄宜克，格局偏枯则待运岁调和。知盛衰之机，为推命枢要。',
    metadata: { principle: '盛衰', seed_key: 'tianli:盛衰' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 时位命',
    content: '孟子：天时不如地利，地利不如人和。命为先天之基，运为时位之机，人为后天之参。三者合论，不可偏废。',
    metadata: { principle: '三才', seed_key: 'tianli:时位' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 德性转气',
    content: '《太上感应篇》：祸福无门，惟人自召。命盘示气机之倾向，德行可移转气机之走向。推命当劝迁善，不助长迷信依赖。',
    metadata: { principle: '德性', seed_key: 'tianli:德性' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 象数理',
    content: '易有象数理：象为表象，数为节律，理为法则。八字为象，大运流年为数，五行生克为理。三者贯通，推演乃明。',
    metadata: { principle: '象数理', seed_key: 'tianli:象数理' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 中正平和',
    content: '《中庸》：喜怒哀乐之未发谓之中，发而皆中节谓之和。推命求中和：五行不偏枯，十神不亢激，身心各得其宜。',
    metadata: { principle: '中和', seed_key: 'tianli:中和' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 知命不认命',
    content: '孔子：五十而知天命。知命是明格局与时机，认命是放弃主体性。在知命基础上尽其性、择其时，方为合天理之人事。',
    metadata: { principle: '知命', seed_key: 'tianli:知命' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 顺时逆命',
    content: '顺天时、应地利、尽人事。逆命非抗天，乃在不利时运中守正蓄力，待时而动。推命之「慎」与「宜」皆本此义。',
    metadata: { principle: '顺逆', seed_key: 'tianli:顺时' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 性命双修',
    content: '性者心也，命者身也。推命属命功之显化，修行属性功之涵养。性命双修，方能在命数框架内臻于自在。',
    metadata: { principle: '性命', seed_key: 'tianli:性命' },
  },
  {
    type: 'principle',
    tradition: 'tianli',
    title: '天理 · 推命三戒',
    content: '一戒独断吉凶，当以整体气机论；二戒恐吓牟利，当以劝善为本；三戒代替人事，命盘示倾向而非定数。此三戒为CyberDestiny释象之纲。',
    metadata: { principle: '戒律', seed_key: 'tianli:三戒' },
  },
];
