/** 周易、道家典籍扩展种子 — 启动时增量写入 knowledge_entries */
import type { KnowledgeSeed } from './seeds/types';

export const CLASSICS_EXTENDED: KnowledgeSeed[] = [
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 系辞上传',
    content: '天尊地卑，乾坤定矣。卑高以陈，贵贱位矣。动静有常，刚柔断矣。方以类聚，物以群分，吉凶生矣。',
    metadata: { source: '易经', section: '系辞上' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 坤卦彖传',
    content: '至哉坤元，万物资生，乃顺承天。坤厚载物，德合无疆。含弘光大，品物咸亨。',
    metadata: { source: '易经', hexagram: '坤' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 乾卦象传',
    content: '天行健，君子以自强不息。潜龙勿用，阳在下也。见龙在田，德施普也。',
    metadata: { source: '易经', hexagram: '乾' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 坎卦',
    content: '习坎，重险也。水流而不盈，行险而不失其信。维心亨，乃以刚中也。',
    metadata: { source: '易经', hexagram: '坎' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '易经 · 离卦',
    content: '离，丽也。日月丽乎天，百谷草木丽乎土。重明以丽乎正，乃化成天下。',
    metadata: { source: '易经', hexagram: '离' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 上善若水',
    content: '上善若水。水善利万物而不争，处众人之所恶，故几于道。居善地，心善渊，与善仁，言善信，政善治，事善能，动善时。',
    metadata: { source: '道德经', chapter: 8 },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 知常曰明',
    content: '知常曰明。不知常，妄作凶。知常容，容乃公，公乃全，全乃天，天乃道，道乃久，没身不殆。',
    metadata: { source: '道德经', chapter: 16 },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '道德经 · 无为而无不为',
    content: '道常无为而无不为。侯王若能守之，万物将自化。化而欲作，吾将镇之以无名之朴。',
    metadata: { source: '道德经', chapter: 37 },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '庄子 · 齐物论（节选）',
    content: '天地与我并生，而万物与我为一。既已为一，得丧喜惧乎？故圣人通于天下，而后世莫能伤之。',
    metadata: { source: '庄子', chapter: '齐物论' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '庄子 · 养生主',
    content: '吾生也有涯，而知也无涯。以有涯随无涯，殆已！已而为知者，殆而已矣！',
    metadata: { source: '庄子', chapter: '养生主' },
  },
  {
    type: 'classic',
    tradition: 'wuxing',
    title: '滴天髓 · 论天干',
    content: '天干动而强，地支静而专。天干主表，地支主里。干支配合，方成格局。',
    metadata: { source: '滴天髓' },
  },
  {
    type: 'classic',
    tradition: 'wuxing',
    title: '滴天髓 · 论地支',
    content: '地支藏人元，人元用事。子中藏癸，丑中藏己癸辛。藏干透干，方显真机。',
    metadata: { source: '滴天髓' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '增删卜易 · 起卦总则',
    content: '动爻为机，静爻为体。世应分宾主，用神定所问。旺相则力强，休囚则力弱，月建日辰为纲领。',
    metadata: { source: '增删卜易', topic: '六爻' },
  },
  {
    type: 'glossary',
    tradition: 'bagua',
    title: '世应',
    content: '六爻断事中，世爻代表问卦者自身，应爻代表所问之事或对方。世应相生则顺，相克则阻。',
    metadata: { term: '世应' },
  },
  {
    type: 'glossary',
    tradition: 'bagua',
    title: '纳甲',
    content: '纳甲筮法将干支纳入八卦，以定爻位五行。乾纳甲壬，坤纳乙癸，震纳庚，巽纳辛，坎纳戊，离纳己，艮纳丙，兑纳丁。',
    metadata: { term: '纳甲' },
  },
  {
    type: 'glossary',
    tradition: 'wuxing',
    title: '十神',
    content: '以日干为我，同我者为比劫，生我者为印星，我生者为食伤，克我者为官杀，我克者为财星。十神定人事象意。',
    metadata: { term: '十神' },
  },
  {
    type: 'glossary',
    tradition: 'wuxing',
    title: '大运',
    content: '十年一运，阳男阴女顺行，阴男阳女逆行。大运管十年主旋律，与流年、命局合参。',
    metadata: { term: '大运' },
  },
  {
    type: 'classic',
    tradition: 'dao',
    title: '黄庭经 · 守一',
    content: '人能守一，使一不散，则神自灵。守一者，守中黄也。中黄者，脾也，土也，中央之德。',
    metadata: { source: '黄庭经' },
  },
  {
    type: 'classic',
    tradition: 'fengshui',
    title: '青囊经 · 气感',
    content: '气感而通，神感而应。山川形势，皆气之聚散。乘气而行，因形而聚，此风水之大旨也。',
    metadata: { source: '青囊经' },
  },
  {
    type: 'classic',
    tradition: 'bagua',
    title: '周易 · 复卦',
    content: '复，其见天地之心乎？一阳来复，生于子月。七日来复，天行也。利有攸往，刚长也。',
    metadata: { source: '易经', hexagram: '复' },
  },
];
